"""Add AI dimension scores

Revision ID: 0ac69bce895e
Revises: 1fe9d5b1387a
Create Date: 2026-09-21 22:24:43.122982
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '0ac69bce895e'
down_revision: Union[str, None] = '1fe9d5b1387a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('structured_review', sa.Column('user_pain_score', sa.Float(), nullable=True))
    op.add_column('structured_review', sa.Column('business_impact_score', sa.Float(), nullable=True))
    op.add_column('structured_review', sa.Column('evidence_strength_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('structured_review', 'evidence_strength_score')
    op.drop_column('structured_review', 'business_impact_score')
    op.drop_column('structured_review', 'user_pain_score')
    # ### end Alembic commands ###
