"""Initial schema

Revision ID: 1fe9d5b1387a
Revises: 
Create Date: 2026-09-18 15:03:34.463349
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '1fe9d5b1387a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failure_mode',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('retrieval_archetype',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scrape_job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_collected', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_job_source'), 'scrape_job', ['source'], unique=False)
    op.create_table('raw_review',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scrape_job_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('author_handle', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_review_scraped_at', 'raw_review', ['scraped_at'], unique=False)
    op.create_index(op.f('ix_raw_review_source'), 'raw_review', ['source'], unique=False)
    op.create_index('ix_raw_review_source_url', 'raw_review', ['source', 'source_url'], unique=False)
    op.create_table('structured_review',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_review_id', sa.UUID(), nullable=False),
    sa.Column('cleaned_text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('photo_category', sa.String(length=100), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('user_effort_signal', sa.Text(), nullable=True),
    sa.Column('retrieval_archetype_id', sa.UUID(), nullable=True),
    sa.Column('failure_mode_id', sa.UUID(), nullable=True),
    sa.Column('is_retrieval_relevant', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['failure_mode_id'], ['failure_mode.id'], ),
    sa.ForeignKeyConstraint(['raw_review_id'], ['raw_review.id'], ),
    sa.ForeignKeyConstraint(['retrieval_archetype_id'], ['retrieval_archetype.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_review_id')
    )
    op.create_index(op.f('ix_structured_review_photo_category'), 'structured_review', ['photo_category'], unique=False)
    op.create_index(op.f('ix_structured_review_source'), 'structured_review', ['source'], unique=False)
    op.create_table('memory_cue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('structured_review_id', sa.UUID(), nullable=False),
    sa.Column('cue_type', sa.String(length=50), nullable=False),
    sa.Column('cue_value', sa.Text(), nullable=False),
    sa.Column('retention_level', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['structured_review_id'], ['structured_review.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memory_cue')
    op.drop_index(op.f('ix_structured_review_source'), table_name='structured_review')
    op.drop_index(op.f('ix_structured_review_photo_category'), table_name='structured_review')
    op.drop_table('structured_review')
    op.drop_index('ix_raw_review_source_url', table_name='raw_review')
    op.drop_index(op.f('ix_raw_review_source'), table_name='raw_review')
    op.drop_index('ix_raw_review_scraped_at', table_name='raw_review')
    op.drop_table('raw_review')
    op.drop_index(op.f('ix_scrape_job_source'), table_name='scrape_job')
    op.drop_table('scrape_job')
    op.drop_table('retrieval_archetype')
    op.drop_table('failure_mode')
    # ### end Alembic commands ###
