"""add_classification_status

Revision ID: 46038dfd3a08
Revises: 0ac69bce895e
Create Date: 2026-09-22 11:49:22.328112
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '46038dfd3a08'
down_revision: Union[str, None] = '0ac69bce895e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add column with a default value so existing rows are handled safely
    op.add_column('raw_review', sa.Column('classification_status', sa.String(length=50), nullable=False, server_default='unprocessed'))
    
    # Backfill: any raw_review that already has a structured_review must have been classified as relevant
    op.execute(
        "UPDATE raw_review SET classification_status = 'relevant' "
        "FROM structured_review "
        "WHERE raw_review.id = structured_review.raw_review_id"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_review', 'classification_status')
    # ### end Alembic commands ###
