"""add reach_score

Revision ID: 984c087eefec
Revises: 46038dfd3a08
Create Date: 2026-09-29 21:01:02.412874
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '984c087eefec'
down_revision: Union[str, None] = '46038dfd3a08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('structured_review', sa.Column('reach_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('structured_review', 'reach_score')
    # ### end Alembic commands ###
